mediathread/taxonomy/urls.py
from django.conf.urls.defaults import patterns, url
import os.path

media_root = os.path.join(os.path.dirname(__file__), "media")

urlpatterns = patterns(
    'mediathread.taxonomy.views',

    url(r'^$',
        'taxonomy_workspace',
        name='taxonomy-workspace'),

    url(r'^/(?P<vocabulary_id>\d+)/$',
        'taxonomy_workspace',
        name='taxonomy-workspace-view')
)

mediathread/urls.py
import os.path
import analytics
import autocomplete_light
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView, TemplateView
from mediathread.assetmgr.views import AssetCollectionView, AssetDetailView, \
    TagCollectionView
from mediathread.main.views import MigrateCourseView, MigrateMaterialsView, \
    RequestCourseView
from mediathread.projects.views import ProjectCollectionView, ProjectDetailView
from mediathread.taxonomy.api import TermResource, VocabularyResource
from tastypie.api import Api


tastypie_api = Api('')
tastypie_api.register(TermResource())
tastypie_api.register(VocabularyResource())

autocomplete_light.autodiscover()
admin.autodiscover()

analytics.init(settings.SEGMENTIO_API_KEY)

bookmarklet_root = os.path.join(settings.STATIC_ROOT, "bookmarklets")

redirect_after_logout = getattr(settings, 'LOGOUT_REDIRECT_URL', None)

logout_page = (r'^accounts/logout/$',
               'django.contrib.auth.views.logout',
               {'next_page': redirect_after_logout})

if hasattr(settings, 'WIND_BASE'):
    auth_urls = (r'^accounts/', include('djangowind.urls'))
    logout_page = (r'^accounts/logout/$', 'djangowind.views.logout',
                   {'next_page': redirect_after_logout})

## for testing
auth_urls = (r'^accounts/', include('allauth.urls'))


urlpatterns = patterns(
    '',
    (r'^$', 'mediathread.main.views.triple_homepage'),  # Homepage
    (r'^avatar/', include('avatar.urls')),
    (r'^about/$', RedirectView.as_view(url=settings.ABOUT_URL)),
    (r'^help/$', RedirectView.as_view(url=settings.HELP_URL)),
    (r'^terms-of-use/$', TemplateView.as_view(template_name='main/terms-of-use.html')),
    (r'^privacy-policy/$', TemplateView.as_view(template_name='main/privacy-policy.html')),

    (r'^admin/', admin.site.urls),

    # API - JSON rendering layers. Half hand-written, half-straight tasty=pie
    (r'^api/asset/user/(?P<record_owner_name>\w[^/]*)/$',
     AssetCollectionView.as_view(), {}, 'assets-by-user'),
    (r'^api/asset/(?P<asset_id>\d+)/$', AssetDetailView.as_view(),
     {}, 'asset-detail'),
    (r'^api/asset/$', AssetCollectionView.as_view(), {}, 'assets-by-course'),
    url(r'^api/user/courses$', 'courseaffils.views.course_list_query',
        name='api-user-courses'),
    (r'^api/tag/$', TagCollectionView.as_view(), {}),
    (r'^api/project/user/(?P<record_owner_name>\w[^/]*)/$',
     ProjectCollectionView.as_view(), {}, 'project-by-user'),
    (r'^api/project/(?P<project_id>\d+)/$', ProjectDetailView.as_view(),
     {}, 'asset-detail'),
    (r'^api/project/$', ProjectCollectionView.as_view(), {}),
    (r'^api', include(tastypie_api.urls)),

    # Collections Space
    (r'^asset/', include('mediathread.assetmgr.urls')),

    # custom login view
    url(r'^accounts/login/$', 'mediathread.user_accounts.views.login_view', name='login_view'),
    auth_urls,
    logout_page,

    (r'^user_accounts/', include('mediathread.user_accounts.urls')),
    (r'^course/', include('mediathread.course.urls')),

    # Bookmarklet + cache defeating
    url(r'^bookmarklets/(?P<path>analyze.js)$', 'django.views.static.serve',
        {'document_root': bookmarklet_root}, name='analyze-bookmarklet'),
    url(r'^nocache/\w+/bookmarklets/(?P<path>analyze.js)$',
        'django.views.static.serve', {'document_root': bookmarklet_root},
        name='nocache-analyze-bookmarklet'),

    url(r'^captcha/', include('captcha.urls')),

    (r'^comments/', include('django.contrib.comments.urls')),

    (r'^contact/', login_required(
        TemplateView.as_view(template_name="main/contact.html"))),
    (r'^course/request/success/$',
     TemplateView.as_view(template_name="main/course_request_success.html")),
    (r'^course/request/', RequestCourseView.as_view()),

    # Courseaffils
    url(r'^accounts/logged_in.js$', 'courseaffils.views.is_logged_in',
        name='is_logged_in.js'),
    url(r'^nocache/\w+/accounts/logged_in.js$',
        'courseaffils.views.is_logged_in', name='nocache-is_logged_in.js'),

    (r'^crossdomain.xml$', 'django.views.static.serve',
     {'document_root': os.path.abspath(os.path.dirname(__file__)),
      'path': 'crossdomain.xml'}),

    url(r'^dashboard/migrate/materials/(?P<course_id>\d+)/$',
        MigrateMaterialsView.as_view(), {}, 'dashboard-migrate-materials'),
    url(r'^dashboard/migrate/$', MigrateCourseView.as_view(),
        {}, "dashboard-migrate"),
    url(r'^dashboard/sources/',
        'mediathread.main.views.class_manage_sources',
        name="class-manage-sources"),
    url(r'^dashboard/settings/',
        'mediathread.main.views.class_settings',
        name="class-settings"),

    # Discussion
    (r'^discussion/', include('mediathread.discussions.urls')),

    # Manage Sources
    url(r'^explore/redirect/$',
        'mediathread.assetmgr.views.source_redirect',
        name="source_redirect"),

    (r'^jsi18n', 'django.views.i18n.javascript_catalog'),

    logout_page,

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root':
      os.path.abspath(os.path.join(os.path.dirname(admin.__file__), 'media')),
      'show_indexes': True}),

    # Composition Space
    (r'^project/', include('mediathread.projects.urls')),

    # Instructor Dashboard & reporting
    (r'^reports/', include('mediathread.reports.urls')),

    # Bookmarklet Entry point
    # Staff custom asset entry
    url(r'^save/$',
        'mediathread.assetmgr.views.asset_create',
        name="asset-save"),

    (r'^setting/(?P<user_name>\w[^/]*)/$',
     'mediathread.main.views.set_user_setting'),

    (r'^stats/', TemplateView.as_view(template_name="stats.html")),
    (r'^smoketest/', include('smoketest.urls')),

    url(r'^taxonomy/', include('mediathread.taxonomy.urls')),

    url(r'^upgrade/', TemplateView.as_view(
        template_name="assetmgr/upgrade_bookmarklet.html")),

    url(r'^autocomplete/', include('autocomplete_light.urls')),
    ### Public Access ###
    (r'^s/', include('structuredcollaboration.urls')),
)

mediathread/taxonomy/models.py
from django import forms
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template.defaultfilters import slugify


class GenericRelationshipManager(models.Manager):
    def get_for_object(self, obj):
        ctype = ContentType.objects.get_for_model(obj)
        return self.filter(content_type__pk=ctype.pk, object_id=obj.pk)

    def get_for_object_list(self, object_list):
        ctype = ContentType.objects.get_for_model(object_list[0])
        ids = object_list.values_list('id', flat=True)
        return self.filter(content_type__pk=ctype.pk, object_id__in=ids)


class Vocabulary(models.Model):
    name = models.SlugField()
    display_name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    single_select = models.BooleanField(default=False)

    # Map this taxonomy to something else. like a course.
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    objects = GenericRelationshipManager()

    class Meta:
        ordering = ['display_name', 'id']

    def save(self, force_insert=False, force_update=False):
        self.name = slugify(self.display_name)
        super(Vocabulary, self).save(force_insert, force_update)

    def __unicode__(self):
        return self.display_name


class VocabularyForm(forms.ModelForm):
    class Meta:
        model = Vocabulary


class Term(models.Model):
    name = models.SlugField()
    vocabulary = models.ForeignKey(Vocabulary)
    display_name = models.CharField(max_length=20)
    description = models.CharField(null=True, blank=True, max_length=256)
    ordinality = models.IntegerField(null=True, blank=True, default=0)

    class Meta:
        unique_together = ('name', 'vocabulary')
        ordering = ['display_name', 'id']

    def __unicode__(self):
        return "%s, %s" % (self.vocabulary, self.display_name)

    def save(self, force_insert=False, force_update=False):
        self.name = slugify(self.display_name)
        super(Term, self).save(force_insert, force_update)

    def to_json(self):
        return {
            'id': self.id,
            'display_name': self.display_name,
            'description': self.description
        }


class TermForm(forms.ModelForm):
    class Meta:
        model = Term


class TermRelationship(models.Model):
    term = models.ForeignKey(Term)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    objects = GenericRelationshipManager()

    class Meta:
        unique_together = ('term', 'content_type', 'object_id')
        ordering = ['term__display_name', 'id']

mediathread/taxonomy/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from djangohelpers.lib import allow_http, rendered_with
from mediathread.mixins import faculty_only
from mediathread.taxonomy.models import VocabularyForm, Vocabulary, TermForm, \
    Term, TermRelationship


@login_required
@allow_http("GET")
@rendered_with('taxonomy/taxonomy.html')
@faculty_only
def taxonomy_workspace(request):
    vocabularies = Vocabulary.objects.get_for_object(request.course)
    for v in vocabularies:
        v.form = VocabularyForm(instance=v)

    course_type = ContentType.objects.get_for_model(request.course)
    form = VocabularyForm(initial={'name': 'initial',
                                   'content_type': course_type,
                                   'object_id': request.course.id})

    return {
        'vocabularies': vocabularies,
        'vocabulary_form': form,
        'course': request.course,
        'course_type': course_type,
        'term_form': TermForm(),
    }


def update_vocabulary_terms(request, content_object):
    concepts = dict((key[len('vocabulary-'):], request.POST.getlist(key))
                    for key, val in request.POST.items()
                    if key.startswith('vocabulary-'))

    # Retrieve concepts/terms that this object is currently associated with
    associations = TermRelationship.objects.get_for_object(content_object)

    # Remove any unmentioned associations
    for a in associations:
        vocabulary_id = str(a.term.vocabulary.id)
        term_id = str(a.term.id)
        if (not vocabulary_id in concepts or
                not term_id in concepts[vocabulary_id]):
            a.delete()

    content_type = ContentType.objects.get_for_model(content_object)
    for name, terms in concepts.items():
        for term_id in concepts[name]:
            term = Term.objects.get(id=int(term_id))
            TermRelationship.objects.get_or_create(
                term=term,
                content_type=content_type,
                object_id=content_object.id)

mediathread/templates/taxonomy/taxonomy.html
{% extends "dashboard/base_dashboard.html" %}

{% block title %}Course Vocabulary Workspace{% endblock %}

{% block uncompressable_css %}
    <script type="text/javascript" src="{{STATIC_URL}}js/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/backbone/backbone-min.js"></script>
    
    <script type="text/template" id="vocabulary-template">
        <div class="vocabularies">           
            <ul>
                <% for (var i=0; i < vocabularies.length; i++) { %>
                    <li id="vocabulary-wrapper-<%=vocabularies[i].id%>" data-id="<%=vocabularies[i].id%>">
                        <div class="arrow"></div>
                        <div class="vocabulary-display">
                            <a class="display-name" href="#vocabulary-<%=vocabularies[i].id%>"><%=vocabularies[i].display_name%></a>
                            
                          <div class="actions">
                                <a class="icon-link edit-vocabulary-open" href="#">                                                     
                                    <img src="{{STATIC_URL}}img/icons/meth_edit.png" class="edit_icon" alt="Edit vocabulary"  />
                                </a>
                                <a class="icon-link delete-vocabulary"
                                    href="<%=vocabularies[i].id%>">                                                
                                    <img src="{{STATIC_URL}}img/icons/meth_delete.png" class="delete_icon" alt="Delete vocabulary"  />
                                </a>
                            </div>                        
                        </div>
                        <div class="vocabulary-edit" style="display: none">
                            <input id="id_display_name" type="text" name="display_name"
                                maxlength="50" value="<%=vocabularies[i].display_name%>"></input>
                            <input type="hidden" name="vocabulary_id" value="<%=vocabularies[i].id%>"/>
                            <a class="btn-primary edit-vocabulary-close" href="#">
                                <span class="ui-icon ui-icon-closethick">close</span>
                            </a>
                            <a class="btn-primary edit-vocabulary-submit" href="#">
                                <span class="ui-icon ui-icon-check">close</span>
                            </a>
                        </div>
                    </li>
                <% } %>

                <% if (vocabularies.length < 3) { %>
                    <li class="create-vocabulary">
                        <div class="vocabulary-display">
                            <a href="#new-vocabulary" class="icon-link create-vocabulary-open">
                                Create Concept
                                <img src="{{STATIC_URL}}img/icons/meth_addselection.png" alt="Create vocabulary" />
                            </a>
                        </div>
                        <div class="vocabulary-create" style="display: none">
                            <input id="id_display_name" type="text" name="display_name"
                                maxlength="50" value="Type concept name here" class="default">
                            <input type="hidden" name="content_type_id" value="<%=content_type_id%>"/>
                            <input type="hidden" name="object_id" value="<%=course_id%>"/>
                            <a class="btn-primary create-vocabulary-close" href="#">
                                <span class="ui-icon ui-icon-closethick">close</span>
                            </a>
                            <a class="btn-primary create-vocabulary-submit" href="#">
                                <span class="ui-icon ui-icon-check">close</span>
                            </a>
                        </div>
                    </li>
                <% } %>
            </ul>       
            <% for (var i=0; i < vocabularies.length; i++) { %>
                <div id="vocabulary-<%=vocabularies[i].id%>">
                    <h2><%=vocabularies[i].display_name%> Concept</h2>
                    <h3>Terms</h3>
                    <div class="terms">
                        <input type="text" name="term_name" class="left default" value="Type new term name here"/>
                        <a class="btn-primary create-term-submit left" href="#">
                            <img src="{{STATIC_URL}}img/icons/meth_addselection.png" alt="Create term" />
                        </a>
                        
                        <div class="visualclear"></div>
                        <% if (vocabularies[i].term_set.length > 0) { %>
                            <div class="term-container">
                            <% for (var j=0; j < vocabularies[i].term_set.length; j++) { %>
                                <div class="term <% if (j%2 === 0) { %>even<% } else { %>odd<% } %>">
                                    <div class="term-display">
                                        <h5><%= vocabularies[i].term_set[j].display_name %></h5>
                                    
                                        <div class="actions">
                                            <a class="icon-link edit-term-open" href="#">                                                     
                                                <img src="{{STATIC_URL}}img/icons/meth_edit.png" class="edit_icon" alt="Edit term"  />
                                            </a>
                                            <a class="icon-link delete-term"
                                                href="<%=vocabularies[i].term_set[j].id%>">                                                
                                                <img src="{{STATIC_URL}}img/icons/meth_delete.png" class="delete_icon" alt="Delete term"  />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="term-edit" style="display: none">
                                        <input id="id_display_name" type="text" name="term_name"
                                            maxlength="50" value="<%=vocabularies[i].term_set[j].display_name%>">
                                        <a class="btn-primary edit-term-close" href="#">
                                            <span class="ui-icon ui-icon-closethick">close</span>
                                        </a>
                                        <a class="btn-primary edit-term-submit" href="#" data-id="<%=vocabularies[i].term_set[j].id%>">
                                            <span class="ui-icon ui-icon-check">close</span>
                                        </a>
                                    </div>
                                </div>

                            <% } %>
                            </div>
                        <% } %>
                    </div>
                </div>
            <% } %>

            <% if (vocabularies.length < 3) { %>
                <div id="new-vocabulary"></div>
            <% } %>
        </div>
    </script>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{STATIC_URL}}js/app/taxonomy/taxonomy.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/backbone/backbone-tastypie.js"></script>
{% endblock %}

{% block uncompressable_js %}
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var view = new VocabularyListView({
                el: jQuery("#taxonomy"),
                course_id: "{{course.id}}",
                content_type_id: "{{course_type.id}}"
            });
        });
    </script>
{% endblock %}

{% block switchcourse %}{% endblock %}

{% block dashboard_module_header %}
    {% with "help_taxonomy" as help_id %}
    {% with help_taxonomy as default_help_state %}

    <h2>Course Vocabulary <div class="actions">{% include "help/help_button.html" %}</div></h2>    
    
    {% endwith %}{% endwith %}
{% endblock %}

{% block dashboard_module %}
    {% with "help_taxonomy" as help_id %}
    {% with help_taxonomy as default_help_state %}
            
    {% include "help/help_contentarea.html" %}
    
    <div id="taxonomy">
    </div>
{% endwith %}{% endwith %}      
{% endblock %}